### ISSUE TITLE
Bad Output

### ISSUE THREAD

**Issue by Schaggo** [satoshi-ikehata/SDM-UniPS-CVPR2023#5]
Hey Mr. Ikehata, 

Congratulations on the fantastic project! 
I am currently trying to evaluate a couple of BRDF solutions and have run into some problems while trying to run your project. 

I prepared the dataset using the Readme / 7 images @ 3488x3488, 8bit /16bit Adobe sRGB, with and without a mask.
![Screenshot 2023-05-24 203206](https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023/assets/42799099/350ba247-26ef-468a-8710-275a853d1694)
The program was set up with canonical resolution from 128 to 512, pixel_samples from 5000 to 20 000
 and launched with the args: --scalable and --target normal
After the program finishes I get a normal map but the results are different than expected. 

![_resized](https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023/assets/42799099/1c35c81a-07f0-4065-a0e1-c7d345cf6d43)

I have a hunch that the 8GB of VRAM I have at hand may be to blame. 
Do you maybe have a tip on what to look at or how to better prepare my dataset?

Thank you for your time!

**Comment by satoshi-ikehata** [comment]
Could you share the result with the object mask? Some failure cases occur when there are drastic differences of the amount of shading variations between foreground and background regions.

Another major failure case is when the scene is illuminated only from frontal light sources. Can you explain your illumination conditions?

**Comment by yyeboah** [comment]
@Schaggo Out of curiosity, I'm wondering how you're ensuring that the human subject stays fixed between frames? Are you using a dedicated capture hardware ?

**Comment by satoshi-ikehata** [comment]
I ran my software on the images that I took screenshots from your post. The results are much better than yours even with them. Please confirm that you successufuly loaded pretrained models.
![normal](https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023/assets/6338753/ce78d00e-d952-4fe4-b973-86a1e786243c)

**Comment by Schaggo** [comment]
@satoshi-ikehata  The normals I posted are produced without the mask. Using a mask results in a black image with a funky stripe in the middle.

I just saw your new answer. Wow, that looks better than I hoped.
I will try once more to set up that project to rule out any dependency issues and report back.

**Comment by Schaggo** [comment]
@yyeboah 
The system captures at a relatively high frame rate on all cameras. The resulting images are then aligned utilizing optical flow.

**Comment by Schaggo** [comment]
@satoshi-ikehata Ok, the issue was that I was pointing to the checkpoint file not the checkpoint directory ... 
Thank you for your help and sorry for the hustle!

**Comment by Schaggo** [comment]
Sorry, to bother again. 

When I use a mask, this happens: 

<img width="499" alt="image" src="https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023/assets/42799099/a37ba069-ac7c-4e4a-8bbc-f1e489d55d34">

any idea what might be happening?

**Comment by satoshi-ikehata** [comment]
I'm not sure what exactly your problem is, but if it is related to only being able to recover a specific part, please ensure that the size of the input images and the foreground mask are exactly the same.

**Comment by satoshi-ikehata** [comment]
Using an A6000 can be helpful, but it may not significantly speed up the process. The most straightforward way to accelerate computation is to reduce either the image size or the number of images. Fundamentally more efficient method is one of my interests as well. However, it is something that would fall under future work of this research.

**Comment by Schaggo** [comment]
All right, I think I understand.
 
Again, Thank you for your help, and have a nice weekend.
